"""Regenerate src/noesek/data/kwp_skills.py from an anthropics/knowledge-work-plugins
checkout (Apache-2.0; business backbone, batch 2 / item 86).

Usage: python scripts/build_kwp_seed.py /path/to/knowledge-work-plugins \
         --categories customer-support operations marketing

Whole categories only - no cherry-picking inside a category, so the seed's
provenance stays auditable category-by-category. Each emitted skill carries a
provenance header (repo, path, license). Re-run to refresh; the checked-in
output is what ships.
"""
import argparse
import re
from pathlib import Path

MAX_STEPS_CHARS = 3900  # skill_library SkillInput.steps cap is 4000


def parse_skill(path: Path):
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not m:
        return None
    fm, body = m.group(1), m.group(2).strip()
    name = re.search(r"^name:\s*(.+)$", fm, re.M)
    desc = re.search(r"^description:\s*(.+)$", fm, re.M)
    if not name or not desc:
        return None
    body = re.sub(r">\s*If you see unfamiliar placeholders.*?CONNECTORS\.md\).\n?",
                  "", body)  # Cowork-environment pointer; not meaningful here
    return {"name": name.group(1).strip(), "description": desc.group(1).strip(),
            "body": body[:MAX_STEPS_CHARS]}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("checkout")
    ap.add_argument("--categories", nargs="+", required=True)
    args = ap.parse_args()
    root = Path(args.checkout)
    skills = []
    for cat in args.categories:
        for smd in sorted((root / cat / "skills").glob("*/SKILL.md")):
            parsed = parse_skill(smd)
            if parsed:
                skills.append({"category": cat,
                               "source_path": str(smd.relative_to(root)), **parsed})
    out = ['"""GENERATED by scripts/build_kwp_seed.py from anthropics/knowledge-work-plugins',
           '(Apache-2.0, LICENSE in that repo; attribution in THIRD_PARTY_NOTICES.md).',
           'Do not edit by hand - re-run the generator against a fresh checkout."""', "",
           "KWP_SKILLS = ["]
    for s in skills:
        out.append(f"    {{'category': {s['category']!r}, 'name': {s['name']!r}, "
                   f"'source_path': {s['source_path']!r},")
        out.append(f"     'description': {s['description']!r},")
        out.append(f"     'body': {s['body']!r}}},")
    out.append("]")
    dest = Path(__file__).resolve().parent.parent / "src/noesek/data/kwp_skills.py"
    dest.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"{len(skills)} skills -> {dest}")


if __name__ == "__main__":
    main()
